export type CategoryId =
  | "biryani"
  | "tandoor"
  | "chinese"
  | "north-indian"
  | "rolls-burgers"
  | "pasta-pizza"
  | "rice-noodles"
  | "breads"
  | "desserts"
  | "beverages";

export type SpiceLevel = 0 | 1 | 2 | 3;

/** Provenance travels with the image, not in someone's memory. */
export interface ImageRecord {
  src: string;
  /** 20px base64 LQIP, generated by scripts/fetch-images.mjs. */
  blurDataURL?: string;
  width?: number;
  height?: number;
  sourceUrl?: string;
  license?: string;
  licenseUrl?: string;
  creator?: string;
  /** True when the licence obliges us to show a credit line in the UI. */
  attributionRequired?: boolean;
}

export interface Dish {
  id: string;
  name: string;
  category: CategoryId;
  /** One line. Shown on the card. */
  blurb: string;
  /** Fuller copy for the modal. */
  description: string;
  /** PLACEHOLDER — see data/menu.ts header. */
  price: number;
  veg: boolean;
  spice: SpiceLevel;
  /** Minutes. Drives the "under 15 min" filter and nothing else. */
  prepMinutes: number;
  allergens: string[];
  portion: string;
  /**
   * True for the six items added to populate Breads and Beverages, which the
   * twenty attested dishes leave empty. Rendered with a marker so they are
   * visibly distinguishable from what is actually on the board.
   */
  unverified?: boolean;
  /** Openverse/Commons search term used by scripts/fetch-images.mjs. */
  imageQuery: string;
}

export interface Category {
  id: CategoryId;
  label: string;
}

export interface Hall {
  id: string;
  /** Short code, set in mono throughout. */
  code: string;
  name: string;
  /**
   * Degrees clockwise from north, PFC at the ring entrance.
   * APPROXIMATE — eyeballed from the campus layout, not surveyed.
   */
  bearing: number;
  /** 1 = on the PAN Loop itself, 2 = off it on a spur. */
  tier: 1 | 2;
  /** Deterministic, drives ETA and fee. Not a measurement. */
  distance: number;
}

export interface CartLine {
  dishId: string;
  qty: number;
}

export interface CartState {
  lines: CartLine[];
  hallId: string | null;
  treatMode: boolean;
  heads: number;
}

export interface OrderPayload {
  name: string;
  phone: string;
  hallId: string;
  room: string;
  payment: "cash" | "upi";
  notes: string;
  lines: CartLine[];
  total: number;
}

export interface OrderResult {
  orderId: string;
  etaMinutes: number;
}

export interface ReservationPayload {
  date: string;
  time: string;
  party: number;
  name: string;
  phone: string;
  note: string;
}

export interface ReservationResult {
  bookingRef: string;
  confirmedAt: string;
}

export interface ReviewPayload {
  rating: number;
  name: string;
  body: string;
}
