// GENERATED by scripts/fetch-images.mjs — do not edit by hand.
// Re-run with: npm run images  (add -- --force to refetch everything)
//
// Provenance ships with the data. Every record carries where the image came
// from, under what licence, and by whom, so the credits page and the in-UI
// attribution lines are derived rather than remembered.

import type { ImageRecord } from "@/lib/types";

export const IMAGES: Record<string, ImageRecord> = {
  "chilli-chicken": {
    "src": "/images/dishes/chilli-chicken.jpg",
    "width": 1024,
    "height": 723,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAA4APu1iqU2ppaQiMAgBMB2JbACdMoADSuTjiYc3bPpQAP0nkNoWkHSOuko40wVxtwEq7SjonBgXIkkzILMZwTZ6bN3C/KTLChrF019mJ8SE05orEYMsm137h/UzZWKAAA==",
    "sourceUrl": "https://www.flickr.com/photos/7914713@N05/40712422042",
    "license": "PDM 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "creator": "Graham Steel",
    "attributionRequired": false
  },
  "chicken-mughlai-biryani": {
    "src": "/images/dishes/chicken-mughlai-biryani.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdMoR3ACPgwOrZKuF4+R0d4AD+zYAbyKX/MMn6jK0h6dT05FjgU70UCiY8NTT2Ug2TmoDEogsbOdHrKbP5VnCFkjuea3ZzWzfVPf8bETrjFm+uQgVk17x5MdxTmsa5+AAA",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=15913726",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
    "creator": "Miansari66",
    "attributionRequired": false
  },
  "tandoor-chicken-biryani": {
    "src": "/images/dishes/tandoor-chicken-biryani.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACsAYzQz9SARQIVGL05j7wAzjWwFf7aIu7UgFHO4cHfWIVi0urNQGijH4tWEubh1rovH0ob7izE2ELDredO3cs9RUYpgedwX6oLmCC4Nq/HgbnNBjULGNU+sokg+rW6L8fUyWjav6eJMIIae5GAGAA=",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mandhi_Dijaj-Emarat_Hotel_Kalamassery-Kerala-IMG_20210131_130053.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "creator": "Ranjithsiji",
    "attributionRequired": true
  },
  "boneless-garlic-chicken": {
    "src": "/images/dishes/boneless-garlic-chicken.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdL1yB78NNpy2XQCQAFvxXAAD2QgcMWnkctFQJYA4WJHw76oyKynEZbSPGPFJZiCko29OJwsKjRPYd40Sj9IDG9vshrD7WA6rpa3RWl0Ri2X9D0GvEEXn9lp4KloE5oiwYEFR8bWofkgkx36ca7qVkSywxkYfjrD8+sdE17eFQ3GAAAA==",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=131207982",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
    "creator": "Jan Helebrant",
    "attributionRequired": false
  },
  "paneer-lamba": {
    "src": "/images/dishes/paneer-lamba.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACxGwAViK1RLK60GSUbIGVAAPyye9/uIBxVUQ9/S1e/V3te7wpLOjqREPFRnBAJ4N2A4RyeLQC3hFdUfwuhBKO000lbOePNtA01HeHzS424JZ76Dsoubm1c0eGPUBVqxwa8jsccsOnBn8rDgzP1TmenGq27oXC+nNnY9a31IAPvjwFkXFUv+AA=",
    "sourceUrl": "https://wordpress.org/photos/photo/6376a2a4b2/",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "Vishnu Chandra",
    "attributionRequired": false
  },
  "chicken-lollipop": {
    "src": "/images/dishes/chicken-lollipop.jpg",
    "width": 1280,
    "height": 960,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbAC7ACP9+QbdlRwTL+Xx+gAA/jv1ZkcOBSV2vtnxLknDnzl5I2rPGivKl2jujAgztySKfK5fZ+My2LIFvVeCl86FmopSEUrn92rvHkgc84pL6NdXFf4peAia+94fJmsTWjyPKrfLn3S3QzXJwgAA",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chicken_lollipop_in_Goa.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "creator": "Peiling Tan from Singapore, Singapore",
    "attributionRequired": true
  },
  "honey-chilli-potato": {
    "src": "/images/dishes/honey-chilli-potato.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JZgCdMoMYAEArNpX9zdSOnQw8AP7Q618kkQYwKr/NTEb2VYO/VvubokHcGfhmEEEP3HuWBTg96tiIoa86pVcrNHUveTOAskqiRQtLgqwO+AONKGuJFEqAi8pKFmReLgAAAA==",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Crispy_honey_chilli_potato.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "creator": "Hrishikes",
    "attributionRequired": true
  },
  "chicken-butter-masala": {
    "src": "/images/dishes/chicken-butter-masala.jpg",
    "width": 720,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoLABQAPu1iqU2ppaOiMAgBMB2JbACdMoR4J3AAI9WdA4OqdO8dqwAAy0dsCG/ZksgYxcLSX8nT5bRMfMJQQq7JpEVKPW9jtsW2i5PG4M89V0QBnsFnT3LIIRim0ytl9QGXfQKVn3kWoge+hjKIeUTG1b1pVHGdircF5xt1v2P+P+be9d12mm/u29y34/6CV8mbkQNiWQW7IdOsRmAAAA==",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=154416407",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
    "creator": "Abithavelu",
    "attributionRequired": false
  },
  "chicken-kolhapuri": {
    "src": "/images/dishes/chicken-kolhapuri.jpg",
    "width": 1600,
    "height": 852,
    "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JbACdABAcYtwQyplJSgAA/matPnJ/gnpPhRJq5npYLIIxid9wQ6+NbQv+wI+XbCZ1UC+OY0JxdHI5Kt5wNcg4gibNwk04J5lctxmkb1xojjcHjYWdDc33QvipRKKjct7Y+kAAAAA=",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chicken_Curry_with_Roti(Indian_Bread).jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "creator": "UserWiki",
    "attributionRequired": true
  },
  "chicken-rashmi-masala": {
    "src": "/images/dishes/chicken-rashmi-masala.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JaACdMoGv/gLsOIZOnIxQbImJaAD9zYEb4LJ9ghSnYFRxmmfIeGyztsB8aTt2CWAT28kaM8FnZKGC/qHCvUkGpHPqLPsHu5Dowv9jbuZXBbYBe5PNlItGmO8cmoWGB9vnPNj6RU24MixYgwsPXw7gOcRN/URZaXX91LcfeOPRn/kRtAa0USdhWAAAAA==",
    "sourceUrl": "https://wordpress.org/photos/photo/6076a663a9/",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "Bigul Malayi",
    "attributionRequired": false
  },
  "chicken-keema-lachha": {
    "src": "/images/dishes/chicken-keema-lachha.jpg",
    "width": 1200,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACQBACdASoPABQAPu1iqU2ppaOiMAgBMB2JaACdMoBOACjn1+zO8QG07BVKLhgA/e5KZ2IDNLkQ/38NzsZBN3jsmsDA4oLpsqCfEKr1sfWQEE/cUQ++nYqSfNTTU3ZPOp12biU09TPvrD2tn/cHW8NcXv3v8QglNSgqPx4G52mCNhnWZY8Lmd2Dq2JfIELN6Cha3V2AAAA=",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kheema_Mutter.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "creator": "Nithajay",
    "attributionRequired": true
  },
  "chicken-tikka-kebab-roll": {
    "src": "/images/dishes/chicken-tikka-kebab-roll.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JaACdMoCGACYpH84kd4ekFPXH6gAA/ulav/Xzs//LTEkVSg7DP1o8v2KFlUpZFC4iEIb7xdQ5Oa/H1v4ZIl43lHEzOm6slVJDnkKoRQxC0L/diLJqT8m+xtwU28jmqeZCWPu/F6MAAA==",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chicken_Kathi_Roll_(5646735923).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "creator": "Andy Mitchell from Glasgow, UK",
    "attributionRequired": true
  },
  "crunchy-chicken-burger": {
    "src": "/images/dishes/crunchy-chicken-burger.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JZgCdMoAluxQOlXLpZpy/fhSGu4AA/koa5fzLeF0iuhxYAb5zWls2bXT7Y0f1paalK6rzCpLLPn44IOQTP5Fg5vQIJAgl1JTf6qsp5RlZ3QgaKEspEurjXBQfvMMoDGCnv0Hct1JOphf7AAQsXwTFpY4d/gKE3AS6hisU5vwCX0x/NV6ZGfOs1KgAAA==",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=129503727",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
    "creator": "Andy Li",
    "attributionRequired": false
  },
  "chicken-tikka-pizza": {
    "src": "/images/dishes/chicken-tikka-pizza.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdMoR3ACL+9sp05TM7uIRIOAAA/pPQQb3njwN9TNGE2iwCfqWmf+wQpIONoG5OuTldiULp0Mg+nq4El5RoY1yXNewfQqbGYs9tmNqgzOf80H06WXEspU6hwiNir1uztORvmqdCIql4ah2b/LaAfPAAAA==",
    "sourceUrl": "https://wordpress.org/photos/photo/35680fd0e0/",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "Bigul Malayi",
    "attributionRequired": false
  },
  "chicken-mixed-sauce-pasta": {
    "src": "/images/dishes/chicken-mixed-sauce-pasta.jpg",
    "width": 1024,
    "height": 576,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JaACdMoACiB8+HExYWbAwAAD+7t62auiXRvrJ7BjAt/8cf6+1+zDjp2/DiJMwUiuR14jg6O/vOfW9on2Fjqep+L5BEzlN+3Dd35LYjpE83B9BTslj8T5Geu+h1ewjadlDB9c4+WfUD5e2hNn/CAAA",
    "sourceUrl": "https://www.flickr.com/photos/164188154@N05/54545176763",
    "license": "PDM 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "creator": "Red Lobster Lover Joe twitter:RLLoverJoe",
    "attributionRequired": false
  },
  "veg-pesto-pasta": {
    "src": "/images/dishes/veg-pesto-pasta.jpg",
    "width": 1600,
    "height": 1096,
    "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoUAA4APu1iqU2ppaOiMAgBMB2JbACdACFU6wWOugetuYUKAADwfCDZuit+VYfxmJv3bKuWlIul6Wp+hHOtZlk/qPzhc5rtLa/AnKiAdo5+AXZgUUrYVfqTkAtJAn+lu95lxxTbKCGL/yAA",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=165398201",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
    "creator": "8w9d",
    "attributionRequired": false
  },
  "triple-rice": {
    "src": "/images/dishes/triple-rice.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JYgCdACLSsPd/CA5SuZnMeISQAP5mhUgOmY0FJKPdyZ+mX93eMTqS+ilcLFDydbrkTlVv7m7P2T+FZWNQHSn1aY6G4Qrx0gDr6HIEXsaRbRabiU78586okzTnb/UlR4Z7aIilC8Q/JLkiXGzaAULTfzNgAA==",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=163554997",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
    "creator": "Mystery6002",
    "attributionRequired": false
  },
  "dal-khichdi-veggies": {
    "src": "/images/dishes/dal-khichdi-veggies.jpg",
    "width": 1600,
    "height": 1067,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JbACdMoR3AB0caDtbwT0CB3KKc8AA/W5/2+Hu+rFVIHtu11mYu8RrJHsy8Gw/xnUKy6gMVrKnhYntU+y3PChBMLH7WhFHa8u+hj8G3L/a+Y33qz8gcra+ACQEO/hwGTiv4ISt7+Ar8o0G9F+yPJFeoPoAAA==",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Masala_Khichadi.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "creator": "Dkgohil",
    "attributionRequired": true
  },
  "butter-naan": {
    "src": "/images/dishes/butter-naan.jpg",
    "width": 800,
    "height": 788,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACQBACdASoUABQAPu1usFIppiSiqAgBMB2JYgC7MxgBeG64k8deEd20kkqKIgAA/tA8efNXKAOb8uebRJiRyk+jiNXmPJK4BKgtg4AcYNwHjMmjj4US/c0C/KzntpMHyOvH1wma19wwHkWpU3GJpkRdrLjH60X84cwLZvlcVNANscH5Gi2zAaeiLRGzkgsYEAA=",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Naan_shiva.jpg",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "creator": "OpenCage",
    "attributionRequired": true
  },
  "lachha-paratha": {
    "src": "/images/dishes/lachha-paratha.jpg",
    "width": 1024,
    "height": 768,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JagCdMoR8eByTGv+cSyzLKwgA2R7kixm9hVsSiSKkaasKgU8s9FumOKAq34Rj/DxjeY5Kj1hM+WjSFxNdXT2+6A+YIxFWpPvOFoAvipnMF8iDoFuRfH/MqQ0bGYAxmHpaHPOiPB44AixYAAA=",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lachha-paratha.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "creator": "Sonia Goyal",
    "attributionRequired": true
  },
  "tandoori-roti": {
    "src": "/images/dishes/tandoori-roti.jpg",
    "width": 1024,
    "height": 823,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADwAwCdASoUABAAPu1iqU2ppaOiMAgBMB2JQBOgBDv5v68quKeU2k6AAP5KDmxAVhNM6yBALvDppM+hx553y5yCtxvOtOnEkfXpVQ1YTBBdnkfY5LPEIVn4TCP/k1DTkCl9K1RIqNwP+htGuB4lzrZAU4Y7zG99GR3II4cPHGHAAA==",
    "sourceUrl": "https://www.rawpixel.com/image/13962567/image-face-hands-frame",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "Unknown",
    "attributionRequired": false
  },
  "brownie-ice-cream": {
    "src": "/images/dishes/brownie-ice-cream.jpg",
    "width": 1024,
    "height": 768,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdMoBOAbT1LwEaBv0Qh+ODwkFYAP2ZFFU+q8P6GF8a8DAa9k9p3uYzMUgZJ93zMUdlaVeOHNxKuQe6JUyyYTXvUwfIY3xti7g60JHW4Fm1fqKxLnqV+H/FvUk2dqDem2txkeiY3cynjsSDrquIKTPD+k2kFGxk4MAA",
    "sourceUrl": "https://www.flickr.com/photos/7633518@N08/54427415751",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "sarahstierch",
    "attributionRequired": false
  },
  "masala-chai": {
    "src": "/images/dishes/masala-chai.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdMoRwAdCslLa+cGKN4uH+2wAA/sv8FWG+l36GGAd70Bj03P+em5Izo9tDSWwHjaeTfTqRfExbDfg8GxCnqL1uyivAYGvDrvV9yyenn83Diru4fNDZ1y8zuYWCwREcpAn6K4jN2bjtjWWtWvKGfUcErP8aKtw1PuIeAAA=",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=144324670",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en/",
    "creator": "Andy Li",
    "attributionRequired": false
  },
  "cold-coffee": {
    "src": "/images/dishes/cold-coffee.jpg",
    "width": 1024,
    "height": 683,
    "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JYwCsABVCXvjCx8jTG4AAzjtW1pTf8GHm9sWbTxPnexJL65CdTMzQomtj9IuERZ9x/TXlNj8FG5qWokYUw5ZEPjSQbpVRk+GnwDMHW+v9lPmN0iO1jWIaKAA=",
    "sourceUrl": "https://www.flickr.com/photos/35034347371@N01/35311547485",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "roland",
    "attributionRequired": false
  },
  "fresh-lime-soda": {
    "src": "/images/dishes/fresh-lime-soda.jpg",
    "width": 1024,
    "height": 683,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JbAAAVLZRGOMrYAD+8qa+8hfRJx6b+OgXlx+nTEHofZCLk1PxEpb6I285XaajwVT0qnK/TbYCtjqymNQ6/JPwiT0lZD50P1fUtu0gwAJ7CgAA",
    "sourceUrl": "https://www.rawpixel.com/image/5917268/image-background-public-domain-celebration",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "Unknown",
    "attributionRequired": false
  },
  "g-biryani": {
    "src": "/images/gallery/g-biryani.jpg",
    "width": 1600,
    "height": 1197,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABwBACdASoUAA8APu1iqU2ppaQiMAgBMB2JQBOmUGXShwuRyncbKvqcg3ZlAAD+e/AaJYUMvCnjg7GLZ70UA0mZv3H1FKpn1GEhCPtbr+vhoYl4MJO4dOaRqkORaZNWxc0RHjtXAkCsJtm//HyHC33nV7XmN5Wg+YU0QgcETAAAAA==",
    "sourceUrl": "https://wordpress.org/photos/photo/778688f198/",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "Md Limon Miah",
    "attributionRequired": false
  },
  "g-tandoor": {
    "src": "/images/gallery/g-tandoor.jpg",
    "width": 1024,
    "height": 768,
    "blurDataURL": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdL1yVhsiuRiyN2S4/9AOIAPukWd6rNSFWIsdmN+b4eGP+nHpeKB4VsU1ZpQJe7B/5fj2vXOFOakb3eWPwVZpMe5sqefynPtOKZDHwpcMhZACeU2TljH2yAqbwaBqVhjRouybG2gvpO0YypsVZCP0Zmgj9jwDONjMkhMhNZaluGfwnRWx1gAA=",
    "sourceUrl": "https://www.flickr.com/photos/96541566@N06/52843424475",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "Juhele_CZ",
    "attributionRequired": false
  },
  "g-street": {
    "src": "/images/gallery/g-street.jpg",
    "width": 1024,
    "height": 683,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAwBACdASoUAA0APu1iqU2ppaOiMAgBMB2JQBWClAOn/AeUj4tQRJbgLgAA/PGmUe4usLC6teLVFYSlV9E8P8fpUFff+W+S7R0KCx+H34O+nQF9bf01Zw5phiLKMcxF6reln2aP51od8ZsLSyGa0fjAvWD+9D/bgrkdFA3PrurUAuRj0yB+wA4JL2pGXWHP8XKzWsxj2VJyvZUnDZ7MdgAA",
    "sourceUrl": "https://www.flickr.com/photos/157635012@N07/50191012291",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creator": "Artem Beliaikin",
    "attributionRequired": false
  },
  "g-chai": {
    "src": "/images/gallery/g-chai.jpg",
    "width": 1200,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoPABQAPu1iqU2ppaOiMAgBMB2JYgAAWpU6G75EeMa8qLqwAAD+72NHJN0MyrpTfMNdvXTGAaAl8fe93m1lRJGqDVQyj8lyTgIroVZdznr6bVAt/4BqPCiqcy1GmqQoM1Jh0OsCImJphhtWVgwECnkwur3m0wAA",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chai_in_a_Glass.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "creator": "Jamie",
    "attributionRequired": true
  },
  "g-thali": {
    "src": "/images/gallery/g-thali.jpg",
    "width": 1600,
    "height": 901,
    "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JagCdMoMjkn/FsCO1iQPjjCZtntRNEAAA/oFj2YNTulAbX8GMaVkkrI4w4HCk7mW6tMgoTim9039y041bTQSfLQIZSDYMVOoxPcIBgu9TXCHk1T1LUSpk8gHlVbA9BBvPjIMiFIdTHe1y0e5cHn9mf7lMkhCg+vLHfQHwAAA=",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Medaillons_of_pork_(Indian_style).jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "creator": "Manfred&amp;Barbara Aulbach",
    "attributionRequired": true
  },
  "g-kolkata": {
    "src": "/images/gallery/g-kolkata.jpg",
    "width": 1024,
    "height": 769,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JQBOgBH3A8grCuu1VnlAA/u9ocsNSnRckyj5fxlDFwxrBh8MsTCHeNZYmjpeIhiMsgcBUPVF48iowKiXjNwOc+dQA9sIQqKAHOPlhNAc+OVWDRK4t62MBvPFvpu5kh4AAAA==",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nirulas_kathi_roll_meal_onboard_IndiGo_airline.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "creator": "V Malik from New Delhi &amp; Pune, India",
    "attributionRequired": true
  },
  "cheese-corn-nugget": {
    "src": "/images/dishes/cheese-corn-nugget.jpg",
    "width": 1600,
    "height": 1064,
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JbACdMoRwABz78eR/SCGm9o/KOAAA/sPRfY72r1JPnDOH8DGvQ/fxV9WEZaI78wuySRhDiL+a5vnN8UoCymWAMIW6TijcqvY4gE9mEGStkZo9ngzbEDduNYcxeU739aGFtvFrGqHl6rtipDjqAAAA",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Broodje_kroket_-_Febo_-_03.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "creator": "Andy Mabbett",
    "attributionRequired": true
  },
  "hero-pfc": {
    "src": "/images/hero/hero-pfc.jpg",
    "width": 1600,
    "height": 1237,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JbAC7H8Agsg7zZTKt2IAA/vEgtHhCptIWSkX13W2xmW1de7IXVrXo7vPm3xHhZbXopkVyu5kqaLTEESUxWsJFs8wIQpElRzAcNJbsBpY9GTQZ34yFI4vY+Z/PD75NJvtHTRn+aKo5UjEbeIYloof7LtzvF7YyF/3/JBW/5NmxX1TJuujzhWDOwb9MGsAA",
    "sourceUrl": "https://restaurant-guru.in/PAN-Loop-Food-Centre-Kharagpur",
    "license": "© rights reserved — used with credit",
    "licenseUrl": "https://restaurant-guru.in/PAN-Loop-Food-Centre-Kharagpur",
    "creator": "via Restaurant Guru",
    "attributionRequired": true
  }
};

export function imageFor(id: string): ImageRecord | undefined {
  return IMAGES[id];
}
